server:
  port: 9003
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloudsc
    username: cloudsc
    password: psd2021
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
mybatis:
  mapper-locations: classpath:mapper/*.xml