server:
  port: 9002
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudsc
    driver-class-name: org.postgresql.Driver
    username: cloudsc
    password: psd2021
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8090
      eager: true
mybatis:
  mapper-locations: classpath:mapper/*.xml