server:
  port: 8093
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudsc
    driver-class-name: org.postgresql.Driver
    username: cloudsc
    password: adc2342wr
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8890
      eager: true
mybatis:
  mapper-locations: classpath:mapper/*.xml