server:
  port: 9002
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudsc?currentSchema=scdemo
    driver-class-name: org.postgresql.Driver
    username: cloudsc
    password: psd2021
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8090
      eager: true
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-seata
mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  client:
    undo:
      log-table: scdemo.undo_log